// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NEI.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace NEI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601234714_RemoveColumnsNotNullRiskZone")]
    partial class RemoveColumnsNotNullRiskZone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NEI.CloseApproach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApproachDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("APPROACH_DATE");

                    b.Property<int>("AsteroidId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ASTEROID_ID");

                    b.Property<decimal>("MissDistanceKm")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("MISS_DISTANCE_KM");

                    b.Property<string>("OrbitingBody")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ORBITING_BODY");

                    b.Property<decimal>("RelativeVelocityKm")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("RELATIVE_VELOCITY_KM");

                    b.HasKey("Id");

                    b.HasIndex("AsteroidId");

                    b.ToTable("DB_CLOSE_APPROACH");
                });

            modelBuilder.Entity("NEI.Models.Asteroid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AbsoluteMagnitude")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("ABSOLUTE_MAGNITUDE");

                    b.Property<decimal>("EstimatedDiameterMaxKm")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("ESTIMATED_DIAMETER_MAX_KM");

                    b.Property<decimal>("EstimatedDiameterMinKm")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("ESTIMATED_DIAMETER_MIN_KM");

                    b.Property<bool>("IsPotentiallyDangerous")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_POTENTIALLY_DANGEROUS");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("NasaId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NASA_ID");

                    b.HasKey("Id");

                    b.HasIndex("NasaId")
                        .IsUnique();

                    b.ToTable("DB_ASTEROIDS");
                });

            modelBuilder.Entity("NEI.RiskAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ASSESSED_AT");

                    b.Property<int>("AsteroidId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("MissDistanceKm")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("MISS_DISTANCE_KM");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(7)")
                        .HasColumnName("RISK_LEVEL");

                    b.Property<decimal>("SafeDistanceThresholdKm")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("SAFE_DISTANCE_THRESHOLD_KM");

                    b.HasKey("Id");

                    b.HasIndex("AsteroidId");

                    b.ToTable("DB_RISK_ASSESSMENTS");
                });

            modelBuilder.Entity("NEI.RiskZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertLevel")
                        .HasColumnType("VARCHAR2(6)")
                        .HasColumnName("ALERT_LEVEL");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("LONGITUDE");

                    b.Property<decimal?>("RadiusKm")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("RADIUS_KM");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REGION_NAME");

                    b.Property<int?>("RiskAssessmentId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RISK_ASSESSMENT_ID");

                    b.HasKey("Id");

                    b.HasIndex("RiskAssessmentId");

                    b.ToTable("DB_RISK_ZONE");
                });

            modelBuilder.Entity("NEI.CloseApproach", b =>
                {
                    b.HasOne("NEI.Models.Asteroid", "Asteroid")
                        .WithMany()
                        .HasForeignKey("AsteroidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asteroid");
                });

            modelBuilder.Entity("NEI.RiskAssessment", b =>
                {
                    b.HasOne("NEI.Models.Asteroid", "Asteroid")
                        .WithMany()
                        .HasForeignKey("AsteroidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asteroid");
                });

            modelBuilder.Entity("NEI.RiskZone", b =>
                {
                    b.HasOne("NEI.RiskAssessment", "RiskAssessment")
                        .WithMany()
                        .HasForeignKey("RiskAssessmentId");

                    b.Navigation("RiskAssessment");
                });
#pragma warning restore 612, 618
        }
    }
}
